apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spinnaker.fullname" . }}-s3-config
  labels:
    app: {{ template "spinnaker.fullname" . }}
data:
  credentials: |
    [default]
    aws_access_key_id={{ .Values.minio.accessKey }}
    aws_secret_access_key={{ .Values.minio.secretKey }}
