apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "spinnaker.fullname" . }}-clouddriver
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: clouddriver
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap/spinnaker-config.yaml") . | sha256sum }}
      labels:
        app: {{ template "spinnaker.fullname" . }}
        component: clouddriver
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "spinnaker.serviceAccountName" . }}
      containers:
        - image: {{ .Values.images.clouddriver }}
          name: clouddriver
          ports:
            - containerPort: 7002
              name: clouddriver
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: {{ template "spinnaker.fullname" . }}-spinnaker-config
            - mountPath: /tmp/registry
              name: {{ template "spinnaker.fullname" . }}-registry
          readinessProbe:
            httpGet:
              path: /health
              port: 7002
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: {{ template "spinnaker.fullname" . }}-spinnaker-config
          configMap:
            name: {{ template "spinnaker.fullname" . }}-spinnaker-config
        - name: {{ template "spinnaker.fullname" . }}-registry
          secret:
            secretName: {{ template "spinnaker.fullname" . }}-registry
