apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "spinnaker.fullname" . }}-gate
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: gate
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap/spinnaker-config.yaml") . | sha256sum }}
      labels:
        app: {{ template "spinnaker.fullname" . }}
        component: gate
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "spinnaker.serviceAccountName" . }}
      containers:
        - image: {{ .Values.images.gate }}
          name: gate
          ports:
            - containerPort: 8084
              name: gate
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: {{ template "spinnaker.fullname" . }}-spinnaker-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 30
            timeoutSeconds: 1
      volumes:
        - name: {{ template "spinnaker.fullname" . }}-spinnaker-config
          configMap:
            name: {{ template "spinnaker.fullname" . }}-spinnaker-config
